insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (1, 'HEBDOMADAIRE', 'VISA', 'OUI');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (2, 'HEBDOMADAIRE', 'PAYPAL', 'OUI');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (3, 'HEBDOMADAIRE', 'CARTE BLEU', 'NON');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (4, 'MENSUEL', 'VISA', 'OUI');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (5, 'MENSUEL', 'PAYPAL', 'NON');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (6, 'MENSUEL', 'CARTE BLEU', 'NON');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (7, 'ANNUEL', 'VISA', 'OUI');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (8, 'ANNUEL', 'PAYPAL', 'NON');
insert into AUTORISATION_PAIEMENT (ID, ABONNEMENT, TYPE_A, VALIDITE) values (9, 'ANNUEL', 'CARTE BLEU', 'OUI');
